[package]
name = "sahayak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
dialoguer = "0.11.0"
indicatif = "0.17.7"
serde = "1.0.196"
